# Development environment properties
spring:
  application:
    name: the-crud
  profiles:
    active: dev
  # MySQL-related properties:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root123
  # Jackson-related configuration:
  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  servlet:
    contextPath: /the-crud

# Spring actuator-related properties:
management:
  endpoint:
    beans:
      access: unrestricted
    env:
      access: unrestricted
  endpoints:
    web:
      exposure:
        include: '*'

# Logging level configuration:
logging:
  level:
    idv:
      clu:
        the:
          crud:
            module: INFO

# Mybatis related properties:
mybatis:
  configuration:
    map-underscore-to-camel-case: true

# Encryption-related setting:
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    keyObtentionIterations: 1000
    password: ruruguruguru
    poolSize: 1
    providerName: SunJCE
    saltGeneratorClassname: org.jasypt.salt.RandomSaltGenerator
    stringOutputType: base64

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  writer-with-default-pretty-printer: true

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/the_crud?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true

---
spring:
  config:
    activate:
      on-profile: container
  datasource:
    url: jdbc:mysql://mysql:3306/the_crud?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true
